version: '3'
services:
    nginx:
        container_name: nginx
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs:/etc/nginx/certs # ここに証明書を設置する
    mirakurun:
        build:
            context: mirakurun
        container_name: mirakurun
        #cap_add:
        #    - SYS_NICE
        #    - SYS_ADMIN
        privileged: true
        ports:
            - "40772:40772"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mirakurun/conf:/usr/local/etc/mirakurun
            - ./mirakurun/db:/usr/local/var/db/mirakurun
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/pt3video0:/dev/pt3video0
            - /dev/pt3video1:/dev/pt3video1
            - /dev/pt3video2:/dev/pt3video2
            - /dev/pt3video3:/dev/pt3video3
            #- /dev/bus/usb/00x/00x # card reader
        #restart: always

    mysql:
        image: mariadb:10.4
        container_name: mysql
        volumes:
            - mysql-db:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_ROOT_PASSWORD: epgstation
            MYSQL_DATABASE: epgstation
            TZ: "Asia/Tokyo"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --performance-schema=false --expire_logs_days=1
        #restart: always

    epgstation:
        build:
            context: epgstation
            args:
                - CPUCORE=2
        container_name: epgstation
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./epgstation/config:/usr/local/EPGStation/config
            - ./epgstation/data:/usr/local/EPGStation/data
            - ./epgstation/thumbnail:/usr/local/EPGStation/thumbnail
            - ./epgstation/logs:/usr/local/EPGStation/logs
            - ./recorded:/usr/local/EPGStation/recorded
        environment:
            TZ: "Asia/Tokyo"
            VIRTUAL_HOST: "localhost"
            VIRTUAL_PORT: 8888
            CERT_NAME: "default"
        links:
            - mirakurun:mirakurun
            - mysql:mysql
        ports:
            - "8888:8888"
            - "8889:8889"
        #user: "1000:1000"
        #restart: always

volumes:
    mysql-db:
        driver: local

